### ISSUE TITLE
Exception raised while saving enum values using TOML format

### ISSUE THREAD

**Issue by yateya** [jacebrowning/datafiles#232] opened 2021-09-02 11:26 UTC
Exception raised while saving dataclass containing enum values using TOML format. 

Sample code to re-produce the bug:

```
import time
from enum import Enum
from datafiles import datafile
from dataclasses import dataclass

class FileOutputType(Enum):
    IN_MESSAGE = 1
    FILESYSTEM = 2

@dataclass
@datafile('config_{self.path}.toml')
class DataPathToml:
    path: str
    path_type: FileOutputType = FileOutputType.IN_MESSAGE

@dataclass
@datafile('config_{self.path}.yml')
class DataPathYaml:
    path: str
    path_type: FileOutputType = FileOutputType.IN_MESSAGE

try:
    p = DataPathToml("blah")
    p.path_type = FileOutputType.FILESYSTEM
    print(p)
    time.sleep(1)
except Exception as ee:
    print("Exception raised!")

p = DataPathYaml("blah")
p.path_type = FileOutputType.FILESYSTEM
print(p.datafile.path)
p.datafile.save()
print(p)
time.sleep(1)
```

The output is 
> Exception raised!
> DataPathYaml(path='blah', path_type=<FileOutputType.FILESYSTEM: 2>)

Using:
- datafiles 0.15.1 (which uses tomlkit 0.7.2)
- Python 3.8.10
- Ubuntu 20.04

The exception:

> Traceback (most recent call last):
  File "test.py", line 15, in <module>
    p.path_type = FileOutputType.FILESYSTEM
  File "/home/ubuntu/.local/lib/python3.8/site-packages/datafiles/hooks.py", line 123, in wrapped
    mapper.save()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/datafiles/mapper.py", line 258, in save
    text = self._get_text(include_default_values=include_default_values)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/datafiles/mapper.py", line 154, in _get_text
    data = self._get_data(**kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/datafiles/mapper.py", line 111, in _get_data
    data = recursive_update(self._last_data, dataclasses.asdict(self._instance))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/datafiles/utils.py", line 63, in recursive_update
    return _merge(old, new)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/datafiles/utils.py", line 72, in _merge
    old[key] = _merge(old.get(key), value)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tomlkit/container.py", line 569, in __setitem__
    self._replace(key, key, value)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tomlkit/container.py", line 595, in _replace
    self._replace_at(idx, new_key, value)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tomlkit/container.py", line 618, in _replace_at
    value = _item(value)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tomlkit/items.py", line 108, in item
    raise ValueError("Invalid type {}".format(type(value)))
ValueError: Invalid type <enum 'FileOutputType'>

**Comment by jacebrowning** [comment] 2021-09-02 21:39
@yateya Thanks for the clear bug report! I tried to codify it into a test, but your example is passing for me: https://github.com/jacebrowning/datafiles/pull/233

Is it possible you have a 3rd-party enum library installed, such as this: https://pypi.org/project/enum/

**Comment by yateya** [comment] 2021-09-03 04:38
@jacebrowning thank for the fast response. You are right. I tried the sample code is new clean docker image with only datafiles installed and it works. I am still searching for the conflicting pip module.

**Comment by yateya** [comment] 2021-09-03 06:44
I noticed that exception is raised if I ran the command twice. It seems the exception happens only if there is toml file found.
Here are the steps:

- Used dockerfile to build fresh enviroment:

> FROM ubuntu:20.04
RUN apt update && apt install python3-pip vim -y
RUN pip3 install datafiles

- Built new docker image
> docker build  -t toml-save-exception .

- Start fresh container in interactive mode `docker run -it --rm toml-save-exception`. using vim, I added the code in /root/test_toml.py
- Ran the code 1st time `cd /root && python3 test_toml.py`
- Code worked normally
- Ran the code 2nd time `python3 test_toml.py`
- Exception raised.

List of pip packages installed:

>  Package           Version 
> ----------------- --------
> cached-property   1.5.2   
> classproperties   0.2.0   
> datafiles         0.15.1  
> minilog           2.0.1   
> parse             1.19.0  
> pip               20.0.2  
> ruamel.yaml       0.17.16 
> ruamel.yaml.clib  0.2.6   
> setuptools        45.2.0  
> tomlkit           0.7.2   
> typing-extensions 3.10.0.2
> wheel             0.34.2  
>

**Comment by jacebrowning** [comment] 2021-09-03 15:03
Thanks! I'm able to reproduce the bug now.

The root cause was that `tomlkit.loads()` was returning a `TOMLDocument` rather than a plain `dict`, leading to errors when updating values.

This should be fixed here: https://pypi.org/project/datafiles/0.15.2/

**Closed** 2021-09-03 15:04 UTC
Labels: bug
